import glob

trim_jar = '/projectnb/perissilab/jorofino/conda_root/envs/mcf7_chipseq/share/trimmomatic-0.38-1/trimmomatic.jar'
truseq3_se = '/projectnb/perissilab/jorofino/conda_root/envs/mcf7_chipseq/share/trimmomatic-0.38-1/adapters/TruSeq3-SE.fa'


rule all:
	input:
		fastqc_trim = expand('samples/{day}_{IP}_trimmed.fastq', day=['d0', 'd14'], IP=['gps2E', 'gps2U', 'input'])	

rule fastqc:
	input:
		fastq = 'samples/{day}_{IP}.fastq'
	output:
		fastqc = 'samples/{day}_{IP}_fastqc.html'
	threads: 8
	shell:
		'fastqc -t {threads} {input.fastq}'

rule trimmomatic:
	input:
		fastq = 'samples/{day}_{IP}.fastq',
		fastqc = 'samples/{day}_{IP}_fastqc.html',
		jar = trim_jar,
		adapters = truseq3_se
	output:
		fastq_trim = 'samples/{day}_{IP}_trimmed.fastq'
	log:
		'samples/{day}_{IP}_trimmed.log'
	shell:
		'java -jar {input.jar} SE'
		' -threads {threads}'
		' {input.fastq} {output.fastq_trim}'
		' ILLUMINACLIP:{input.adapters}:2:30:10 LEADING:3 TRAILING:3'
		' SLIDINGWINDOW:4:15 MINLEN:40 2> {log}'

